version: '3'

services:
   web:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 5001:5001
      depends_on: 
         - redis
      environment:
         REDIS_URI: redis://redis:6379
      networks:
         - omnilearning         
      restart: always     

   redis:
      image: "redis:7.0.4"
      ports:
         - "6379:6379"
      expose:
         - 6379
      volumes:
         - redis_data:/bitnami/redis/data
         - /var/log/redis/:/var/log/redis/
         - /var/lib/redis/:/var/lib/redis/
      networks: 
         - omnilearning
      restart: always

volumes:
  redis_data:
   driver: local

networks:
   omnilearning: